stabble adapter
DefiLlama/DefiLlama-Adapters pull request #10522
Opened 2024-06-05 21:47 UTC by stabble-devops

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

##### Twitter Link:

##### List of audit links if any:

##### Website Link:

##### Logo (High resolution, will be shown with rounded borders):

##### Current TVL:

##### Treasury Addresses (if the protocol has treasury)

##### Chain:

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama):

##### Token address and ticker if any:

##### Category (full list at https://defillama.com/categories) *Please choose only one:

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

##### forkedFrom (Does your project originate from another project):

##### methodology (what is being counted as tvl, how is tvl being calculated):

##### Github org/user (Optional, if your code is open source, we can track activity):

2024-06-05 21:48 UTC, llamatester commented
The adapter at projects/stabble exports TVL: 
        
 
 
    solana                    5.75 k
    
    total                    5.75 k

2024-06-05 21:51 UTC, stabble-devops commented
@llamatester  Created PR for listing protocol - https://github.com/DefiLlama/defillama-server/pull/7146

2024-06-06 09:33 UTC, g1nt0ki requested changes
thanks for the PR, but this not very scalable, can you update code to pull pool & token list and compute tvl on chain?

2024-06-06 15:37 UTC, llamatester commented
Error while running adapter at projects/stabble: 
        
 
  
    
    
    TypeError: Cannot use 'in' operator to search for 'vec' in pubkey
    Truncated error stack:
        at IdlCoder.fieldLayout (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@project-serum/anchor/dist/cjs/coder/borsh/idl.js:92:27)
        at Array.map (<anonymous>)
        at Array.map (<anonymous>)
        at weightedSwapTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/stabble/index.js:11:19)
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

2024-06-06 15:42 UTC, llamatester commented
Error while running adapter at projects/stabble: 
        
 
  
    
    
    IdlError: Type not found: {"type":{"defined":{"name":"PoolToken"}}}
    Truncated error stack:
        at IdlCoder.fieldLayout (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@project-serum/anchor/dist/cjs/coder/borsh/idl.js:112:31)
        at Array.map (<anonymous>)
        at Array.map (<anonymous>)
    Error saving cache: Error: ENOENT: no such file or directory, open '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
        at Object.openSync (node:fs:596:3)
        at Object.writeFileSync (node:fs:2322:35)
        at process.saveCache (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/cache.js:152:17)
        at process.emit (node:events:529:35)
        at process.exit (node:internal/process/per_thread:191:15)
        at process.handleError (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/utils/handleError.js:18:11)
        at process.emit (node:events:529:35)
        at emit (node:internal/process/promises:149:20)
        at processPromiseRejections (node:internal/process/promises:283:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/util/local_cache/zlib-1.0/BlockCache.json'
    }

2024-06-06 15:54 UTC, llamatester commented
Error while running adapter at projects/stabble: 
        
 
  
    
    
    TypeError: tokens.map is not a function
    Truncated error stack:
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@defillama/sdk/build/generalUtil.js:139:35
        at sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:366:41)
        at weightedSwapTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/stabble/index.js:25:10)
        at async Promise.all (index 0)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:143:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)

2024-06-06 15:58 UTC, llamatester commented
The adapter at projects/stabble exports TVL: 
        
 
 
    solana                    0
    
    total                    0

2024-06-06 16:06 UTC, llamatester commented
The adapter at projects/stabble exports TVL: 
        
 
 
    solana                    5.75 k
    
    total                    5.75 k

2024-06-06 16:08 UTC, stabble-devops commented
> thanks for the PR, but this not very scalable, can you update code to pull pool & token list and compute tvl on chain?

Thanks for your feedback! I've refactored it. @g1nt0ki

2024-06-06 16:10 UTC, stabble-devops commented on projects/stabble/index.js
> +const WEIGHTED_SWAP_IDL = {
@g1nt0ki I've defined anchor 0.26.0 compatible IDL manually as our contract is written in anchor 0.30.0.

2024-06-06 16:40 UTC, g1nt0ki commented
looks good, thanks for the changes.

2024-06-06 16:40 UTC, merged