Update Hedgehog-Markets support
DefiLlama/DefiLlama-Adapters pull request #12315
Opened 2024-11-15 16:29 UTC by Juici

Adds support for additional markets to the existing Hedgehog-Markets support.
- https://github.com/DefiLlama/DefiLlama-Adapters/pull/11714
- https://github.com/DefiLlama/DefiLlama-Adapters/pull/11719

2024-11-15 16:30 UTC, llamatester commented
Error while running adapter at projects/hedgehog-markets: 
        
 
  
    
    
    Error: 429 Too Many Requests: {"jsonrpc":"2.0","error":{"code":-32429,"message":"max usage reached"}}
    Truncated error stack:
        at ClientBrowser.callServer (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@solana/web3.js/lib/index.cjs.js:4944:18)

2024-11-15 16:35 UTC, llamatester commented
The adapter at projects/hedgehog-markets exports TVL: 
        
 
 
    solana                    78.09 k
    
    total                    78.09 k

2024-11-15 16:36 UTC, llamatester commented
The adapter at projects/hedgehog-markets exports TVL: 
        
 
 
    solana                    78.01 k
    
    total                    78.01 k

2024-11-15 16:51 UTC, g1nt0ki requested changes

2024-11-15 16:51 UTC, g1nt0ki commented on tsconfig.json
can you please revert this

2024-11-15 16:51 UTC, g1nt0ki commented on projects/hedgehog-markets/index.js
sorry, but this is a bit of nightmare to review, can you revert changes to this file to the version in main branch, and include only new code that you want to add?


I did some refactoring/optimization so the file is easy for me to understand, dont want to repeat that.

2024-11-18 14:09 UTC, llamatester commented
Error while running adapter at projects/hedgehog-markets: 
        
 
  
    
    
    Error: Failed to post https://mainnet.helius-rpc.com/?api-key=0109717a-77b4-498a-bc3c-a0b31aa1b3bf
    Truncated error stack:
    
        at Object.post (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/http.js:47:11)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:269:29
        at async runInChunks (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:392:22)
        at async sumTokens2 (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/helper/solana.js:216:20)
        at async tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/hedgehog-markets/index.js:20:3)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:23)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:173:9
        at async Promise.all (index 0)
        at async Promise.all (index 1)

2024-11-18 14:10 UTC, Juici commented on tsconfig.json
Done in [`cc655f7`](https://github.com/DefiLlama/DefiLlama-Adapters/pull/12315/commits/cc655f7b7f1b2d1154812a1c91d6caa9236ea1e1).

2024-11-18 14:33 UTC, g1nt0ki commented on projects/hedgehog-markets/index.js
@Juici thanks for indulging me.

2024-11-18 14:33 UTC, merged