Superfluid TVL calculation fix
DefiLlama/DefiLlama-Adapters pull request #12396
Opened 2024-11-22 10:25 UTC by cincauhangus

Hello, I work with Superfluid team to update the TVL calculation for the Superfluid platform. These are the changes made:

- Consolidating 'vesting TVL' into a single TVL as there is no vesting in Superfluid
   - The new TVL is more representative of the values seen in [Superfluid's Explorer](https://explorer.superfluid.finance/base-mainnet/supertokens)
- Added new chains
- Removed whitelisted & blacklisted Supertokens in favor of `isListed` flag from subgraph

2024-11-22 10:25 UTC, llamatester commented
The adapter at projects/superfluid.js exports TVL: 
        
 
 
    optimism                  45.63 M
    base                      4.00 M
    polygon                   2.72 M
    ethereum                  763.53 k
    arbitrum                  118.02 k
    xdai                      81.52 k
    bsc                       536
    avax                      468
    scroll                    0
    
    total                    53.31 M

2024-11-22 11:18 UTC, g1nt0ki requested changes
hi @cincauhangus thanks for the PR
It is mostly good except for removal of vesting, we have this as a hack, else it wont be fair comparison between streaming protocols.


The reason, we are doing this is, we cant really tell if the token being streamed is already in circulation or not, thats why to be safe, we count all tokens other than gas tokens & stablecoins under vesting

We apply the same rule for all streaming protocols, you can verify it in our codebase, search for `streamingHelper` without this check, streamflow tvl would be over 1B

2024-12-20 17:02 UTC, g1nt0ki commented
bump

2025-01-02 12:36 UTC, cincauhangus commented
Sorry, will send a fix ASAP

2025-02-01 02:56 UTC, cincauhangus commented
recreated PR - https://github.com/DefiLlama/DefiLlama-Adapters/pull/13334

2025-02-01 02:56 UTC, closed without merging