adding support of other btc assets.
DefiLlama/DefiLlama-Adapters pull request #12690
Opened 2024-12-12 20:08 UTC by zluqo

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

##### Twitter Link:

##### List of audit links if any:

##### Website Link:

##### Logo (High resolution, will be shown with rounded borders):

##### Current TVL:

##### Treasury Addresses (if the protocol has treasury)

##### Chain:

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama):

##### Token address and ticker if any:

##### Category (full list at https://defillama.com/categories) *Please choose only one:

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

##### forkedFrom (Does your project originate from another project):

##### methodology (what is being counted as tvl, how is tvl being calculated):

##### Github org/user (Optional, if your code is open source, we can track activity):

2024-12-12 20:08 UTC, llamabutler commented
The adapter at projects/bitflux exports TVL: 
        
 
 
    core                      29.35 M
    
    total                    29.35 M

2024-12-13 10:40 UTC, g1nt0ki commented
hi @zluqo I have added the new pools here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/b8ca31658d4a826eecd4e9a97af5c5b5128b8055

But we dont like putting custom pricing/token mapping in the adapter, prefer doing that on our coins server, this way, all tvl adapters behave the same. How are these tokens bridged to code? suBTC/nexusBTC & pumpBTC.

Is suBTC sumer synth token? if so, I am not sure how 13 suBTC is deposited in your pool when circulating supply is less than 1  https://app.sumer.money/analytics/?chain=810180
![image](https://github.com/user-attachments/assets/d7fcb9a6-dfe0-4f4c-8cde-3c53d2143f2b)

2024-12-13 10:40 UTC, g1nt0ki requested changes
.

2024-12-14 01:11 UTC, xiaohanzhu commented
Thank you for pointing the issue.  We haven't updated the pie chart to include the circulation on Core network (since the lending and CDP engine is not deployed yet).  The suBTC were minted on zklink and bridged to Core.  We just updated the UI to show where the suBTC were minted so you will have a better idea of the collaterals.  Feel free to verify again.

> hi @zluqo I have added the new pools here: [b8ca316](https://github.com/DefiLlama/DefiLlama-Adapters/commit/b8ca31658d4a826eecd4e9a97af5c5b5128b8055)
> 
> But we dont like putting custom pricing/token mapping in the adapter, prefer doing that on our coins server, this way, all tvl adapters behave the same. How are these tokens bridged to code? suBTC/nexusBTC & pumpBTC.
> 
> Is suBTC sumer synth token? if so, I am not sure how 13 suBTC is deposited in your pool when circulating supply is less than 1 https://app.sumer.money/analytics/?chain=810180 ![image](https://private-user-images.githubusercontent.com/99907941/395529793-d7fcb9a6-dfe0-4f4c-8cde-3c53d2143f2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMzgxNjksIm5iZiI6MTczNDEzNzg2OSwicGF0aCI6Ii85OTkwNzk0MS8zOTU1Mjk3OTMtZDdmY2I5YTYtZGZlMC00ZjRjLThjZGUtM2M1M2QyMTQzZjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDAwNTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MThkYWUzZTc0MzBhOTMzNzNjNzJkZjUyNThjY2IxY2Y1MGYxZjcwYzNiNWI5ZDg5NDM2NDIwMGQ5NmYwYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FemKubqL3BkVs7ivZPTVPwW8QRoiPjfn6iVLQl18_-Y)

2024-12-15 08:49 UTC, zluqo commented
@g1nt0ki on your suggestion of adding suBTC, nBTC and pumpBTC to coin server here is the initial commit which includes suBTC only.

https://github.com/BitFluxFi/defillama-server/commit/6da968546a11954364044166a77a3f60686d2c5f

Can you check and let us know if this make sense? I will open PR later.

2024-12-17 02:17 UTC, xiaohanzhu commented
Hi @zluqo please see the updated pie charts.  Let us know if any additional information or fixes are needed for this PR.  Thank you very much for your help!

![image](https://github.com/user-attachments/assets/ad957ee1-4107-4d7b-bf0a-a9b761b7a284)

> hi @zluqo I have added the new pools here: [b8ca316](https://github.com/DefiLlama/DefiLlama-Adapters/commit/b8ca31658d4a826eecd4e9a97af5c5b5128b8055)
> 
> But we dont like putting custom pricing/token mapping in the adapter, prefer doing that on our coins server, this way, all tvl adapters behave the same. How are these tokens bridged to code? suBTC/nexusBTC & pumpBTC.
> 
> Is suBTC sumer synth token? if so, I am not sure how 13 suBTC is deposited in your pool when circulating supply is less than 1 https://app.sumer.money/analytics/?chain=810180 ![image](https://private-user-images.githubusercontent.com/99907941/395529793-d7fcb9a6-dfe0-4f4c-8cde-3c53d2143f2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDE5NzEsIm5iZiI6MTczNDQwMTY3MSwicGF0aCI6Ii85OTkwNzk0MS8zOTU1Mjk3OTMtZDdmY2I5YTYtZGZlMC00ZjRjLThjZGUtM2M1M2QyMTQzZjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAyMTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YzUxMzUxMjQ3MjRjMjQ1ZmU4NTUzYzMxYWNiMmEwNjA5YTU3YmQyNjIzZjI3NGQzMzc2YTAyYWRjNGM2ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.04DFj6K7z6lsiUy0AqpXtLGW9sKWCyp0m926zWFgrC4)

2025-04-30 08:58 UTC, waynebruce0x commented
Can we go ahead and make the required changes please?

2025-04-30 17:26 UTC, xiaohanzhu commented
Please let me know if anything needed on our end, please let me know.  Our pie charts all look correct right now

2025-05-01 10:32 UTC, waynebruce0x commented
https://github.com/DefiLlama/DefiLlama-Adapters/pull/14511/files#diff-a6bb48da4d06a8a1de0c4f1a1ae1e27605d2e5fba51a38d79f8e3522e2f976b7R29

2025-05-01 10:32 UTC, closed without merging