add SSI Protocol TVL adapter
DefiLlama/DefiLlama-Adapters pull request #12893
Opened 2024-12-27 13:30 UTC by shirc

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):
SSI

##### Twitter Link:
https://x.com/SoSoValueCrypto

##### List of audit links if any:
Blocksec: 
https://github.com/blocksecteam/audit-reports/blob/main/solidity/blocksec_sosovaluelabs_ssi_v1.0-signed.pdf
Slowmist Round 1:
 https://github.com/slowmist/Knowledge-Base/blob/master/open-report-V2/smart-contract/SSI%20Protocol%20-%20SlowMist%20Audit%20Report.pdf
Slowmist Round 2:
https://github.com/slowmist/Knowledge-Base/blob/master/open-report-V2/smart-contract/SSI%20Protocol%20Phase2%20-%20SlowMist%20Audit%20Report.pdf

##### Website Link:
https://ssi.sosovalue.com/

##### Logo (High resolution, will be shown with rounded borders):
![image](https://github.com/user-attachments/assets/229a5e51-8daa-472b-a74e-6ce7111dcad9)

##### Current TVL:
1.93M

##### Treasury Addresses (if the protocol has treasury)

##### Chain:
Base

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
mag7-ssi
defi-ssi
meme-ssi
ussi

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama):
The SoSoValue Index (SSI) Protocol is a cutting-edge spot index solution designed to make crypto investments simple and secured.

##### Token address and ticker if any:
- MAG7.ssi: 0x9E6A46f294bB67c20F1D1E7AfB0bBEf614403B55
- DEFI.ssi: 0x164ffdaE2fe3891714bc2968f1875ca4fA1079D0
- MEME.ssi: 0xdd3acDBDc7b358Df453a6CB6bCA56C92aA5743aA
- USSI: 0x3a46ed8FCeb6eF1ADA2E4600A522AE7e24D2Ed18

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Indexes

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

##### forkedFrom (Does your project originate from another project):

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL counts the SSI tokens and USSI token minted.

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/SoSoValueLabs/ssi-protocol

2024-12-27 13:30 UTC, llamabutler commented
The adapter at projects/ssi-protocol exports TVL: 
        
 
 
    base                      1.96 M
    
    total                    1.96 M

2024-12-27 14:43 UTC, g1nt0ki requested changes
hi, thanks for the PR, can you share the vault addresses where the tokens backing the index are kept? we prefer fetching that balance and computing tvl

2024-12-30 10:43 UTC, shirc commented
> hi, thanks for the PR, can you share the vault addresses where the tokens backing the index are kept? we prefer fetching that balance and computing tvl

Yes, we can provide vault addresses. However, some of the indices use vault addresses managed by Ceffu prime wallets instead of Ceffu qualified wallets, which will lead to difficulties in capturing values since mirrox requires mirroring to binance to retrieve values,  making TVL statistics less comprehensive. 

To standardize the TVL calculation method, since our business model is quite similar to Ethena project, and we use similar underlying asset services (e.g. Ceffu for mirroring), we have used Ethena project's calculation method as a reference which involves using total supply. 

These processes have been audited by four independent security audit firms. If needed, we can provide further audit reports for each auditing firm as proof of custody from custodial institutions. We look forward to your reply, and you are welcome to contact us via email: [protocol@sosovalue.com](mailto:protocol@sosovalue.com) for further questions or concerns.

2025-01-08 13:36 UTC, shirc commented
@g1nt0ki Hi, thank you for the feedback, please kindly review our response: 

Vault Addresses for Meme.ssi:
doge: DPQ3EbacSG6gdakZmXwMu7qS6SbpRUjY4a (doge)
eth: 0x55ac87E54019fa2e2156a0fAf13176DcdDFA16ce (shib)
eth: 0x55ac87E54019fa2e2156a0fAf13176DcdDFA16ce (pepe)
sol: CeuKmW1XqgKz4E8JNpZxrysMRsvkEz55qUvm9soqhALY (wif)
sol: CeuKmW1XqgKz4E8JNpZxrysMRsvkEz55qUvm9soqhALY (bonk)
bnb: 0x55ac87E54019fa2e2156a0fAf13176DcdDFA16ce (floki)
SOL GQkn3fPeCV4pH1MGZVHsWPpRdq5ENYnaB8GVwSubjkCZ (popcat)
SOL GQkn3fPeCV4pH1MGZVHsWPpRdq5ENYnaB8GVwSubjkCZ (mew)
ETH 0x605b50f07f46251a7a39fa18c2247fb612f7452f (mog)
SOL GQkn3fPeCV4pH1MGZVHsWPpRdq5ENYnaB8GVwSubjkCZ (pnut)


Vault Addresses for Defi.ssi:
SOL GQkn3fPeCV4pH1MGZVHsWPpRdq5ENYnaB8GVwSubjkCZ (jup)
ETH 0x605b50f07f46251a7a39fa18c2247fb612f7452f (ondo)
eth: 0x55ac87E54019fa2e2156a0fAf13176DcdDFA16ce (link)
eth: 0x55ac87E54019fa2e2156a0fAf13176DcdDFA16ce (uni)
eth: 0x55ac87E54019fa2e2156a0fAf13176DcdDFA16ce (aave)
eth: 0x55ac87E54019fa2e2156a0fAf13176DcdDFA16ce (ena)
eth: 0x55ac87E54019fa2e2156a0fAf13176DcdDFA16ce (mkr)
eth: 0x55ac87E54019fa2e2156a0fAf13176DcdDFA16ce (ldo)
sol: CeuKmW1XqgKz4E8JNpZxrysMRsvkEz55qUvm9soqhALY (pyth)
sol: CeuKmW1XqgKz4E8JNpZxrysMRsvkEz55qUvm9soqhALY (ray)

Vault Addresses for Mag7.ssi:
mag7:
BTC: 1BH4rZH7ptWyjim6fLJDp9t8Jp2DgXiBDM
ETH: 0x3bc6b3146d48fafcfb6be35284295019fbd645e7
SOL: 8yVXip9eFwdmrbTxPqHsuCvVR5ktBdLGz7S1bUpSx7j6
BNB: 0x3bc6b3146d48fafcfb6be35284295019fbd645e7
XRP: rp53vxWXuEe9LL6AHcCtzzAvdtynSL1aVM
DOGE: D5gedqfZm198AyTFVg8NqWFUh8bFTdmKj7
ADA: addr1v9nkv9p0gz83ha7hx0h6pg6lrte0t0dsj8tyersc8np5gegrwwxpp

Please note that Mag7.ssi and USSI is managed by Ceffu prime wallet. We select this wallet solution because we need the MirrorX feature to achieve Mag7.ssi headging - similar to Ethena. 
Due to the characteristics of Ceffu Prime Wallet, there will be a descrepancy between the showing TVL and the actual underlying assets.  Our solution is calculating TVL  using total supply - same as Ethena. Since this method applies to all Tokens in question, we highly suggest Defillama use the Total Supply method for all tokens. 


Attaching Audits Reports for your reference: 
Blocksec:
https://github.com/blocksecteam/audit-reports/blob/main/solidity/blocksec_sosovaluelabs_ssi_v1.0-signed.pdf
Slowmist Round 1:
https://github.com/slowmist/Knowledge-Base/blob/master/open-report-V2/smart-contract/SSI%20Protocol%20-%20SlowMist%20Audit%20Report.pdf
Slowmist Round 2:
https://github.com/slowmist/Knowledge-Base/blob/master/open-report-V2/smart-contract/SSI%20Protocol%20Phase2%20-%20SlowMist%20Audit%20Report.pdf

Looking forward to your response!

2025-01-13 14:32 UTC, g1nt0ki commented
thanks, I have added it

2025-01-13 14:32 UTC, closed without merging