Adding Versa.finance
DefiLlama/DefiLlama-Adapters pull request #2281
Opened 2022-04-13 22:06 UTC by versa-finance-dev

##### Twitter Link: https://twitter.com/versa_finance

##### List of audit links if any: 

##### Website Link: https://versa.finance/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): https://versa.finance/images/pools/versa-versa.svg

##### Current TVL: 549 000$

##### Chain: Astar

##### Coingecko ID (so your TVL can appear on Coingecko): versa

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama): Versa is the decentralized exchange on Astar Network with the yield farming and staking. It has very high APY and simple UI, quite easy to use.

##### Token address and ticker if any: 0xB9dEDB74bd7b298aBf76b9dFbE5b62F0aB05a57b

##### Category (full list at https://defillama.com/categories) *Please choose only one: Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

##### forkedFrom (Does your project originate from another project): PancakeSwap

##### methodology (what is being counted as tvl, how is tvl being calculated):
User locked Versa or Versa LP to dapp contract and claim rewards

2022-04-14 07:30 UTC, g1nt0ki requested changes

2022-04-14 07:30 UTC, g1nt0ki commented on projects/Versa/index.js
> +    "versa",
can you change this to `astar`, thats the chain name :)

2022-04-14 07:30 UTC, g1nt0ki commented on projects/Versa/index.js
> +    ], "versa")
same here versa -> astar

2022-04-14 07:30 UTC, g1nt0ki commented on projects/Versa/index.js
> +    tvl: versaTvl
can you put the tvl under chain name, like

    methodlogy: ...
    astar: { tvl: versaTvl }

2022-04-14 16:42 UTC, versa-finance-dev commented
@g1nt0ki Thanks, updated, check please

2022-04-14 16:56 UTC, g1nt0ki commented on projects/Versa/index.js
> +    tvl: astarTvl
sorry, you missed to fix this line

2022-04-14 16:56 UTC, g1nt0ki requested changes
still need to fix module.exports

2022-04-14 23:11 UTC, versa-finance-dev commented
Fixed

2022-04-15 11:55 UTC, llamatester commented
Error while running adapter at projects/Versa/index.js: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:206:11
        at processTicksAndRejections (node:internal/process/task_queues:96:5)

2022-04-15 11:56 UTC, merged

2022-04-15 11:59 UTC, g1nt0ki commented
thanks for the PR, fixed the minor bug after merging