Upgrad to show correct TVL for Beanstalk (BEAN)
DefiLlama/DefiLlama-Adapters pull request #2300
Opened 2022-04-15 14:11 UTC by Taimonania

##### Current TVL:
152.78 M as of block 14590383.

##### Chain:
ethereum

##### methodology (what is being counted as tvl, how is tvl being calculated):
Short: Counts all beans and current LPs in the silo.

Long: Calculates currently locked Beans, locked BEAN:ETH Uniswap LP and locked BEAN:3CRV LP and BEAN:LUSD LP on Curve and unwraps underlying tokens to get current TVL.

2022-04-15 14:17 UTC, llamatester commented
The adapter at projects/bean/index.js exports TVL: 
        
 
 
    ethereum                  152.75 M
    
    total                    152.75 M

2022-04-15 15:38 UTC, g1nt0ki requested changes
The code is good, just a minor change on how you fetch token balances.

Also, please take out pool2 and staking part as their own exports.

2022-04-15 15:38 UTC, g1nt0ki commented on projects/bean/index.js
> +        abi: bean_abi["totalDepositedBeans"],
can this be replaced with


      const beanBalance = (await sdk.api.erc20.balanceOf({
        chain: 'ethereum',
        target: BEAN_TOKEN_ADDR,
        owner: BEAN_DIA_ADDR,
        block,
    })).output;
    
  Also, can this be moved to staking?

2022-04-15 15:38 UTC, g1nt0ki commented on projects/bean/index.js
> +    const beanEthLpBalance = (await sdk.api.abi.call({
same, can you count here using `erc20.balanceOf` or you could use `sumTokensAndLPsSharedOwners` from `unwrapLPs` helper

Can you move this value to pool2

2022-04-15 15:38 UTC, g1nt0ki commented on projects/bean/index.js
> +                abi: bean_abi["getTotalDeposited"],
can you also replace the calls here with erc20.balanceOf calls.

hmmm, I see that the curve pools have bean tokens in them, let me check with others if these too must go under pool2

2022-04-16 14:47 UTC, llamatester commented
The adapter at projects/bean/index.js exports TVL: 
        
 
 
    ethereum                  0
    ethereum-staking          30.69 M
    ethereum-pool2            138.82 M
    staking                   30.69 M
    pool2                     138.82 M
    
    total                    0

2022-04-17 17:02 UTC, merged