Added Gale Token
DefiLlama/DefiLlama-Adapters pull request #2585
Opened 2022-05-07 17:33 UTC by niftybrain

##### Twitter Link: https://t.me/galenetworkpublic

##### List of audit links if any: https://github.com/solidproof/projects/blob/main/Gale/SmartContract_Audit_Solidproof_GaleToken.pdf

##### Website Link: https://gale.network

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders): https://gale.network/images/logo-large.png

##### Current TVL: $1.5M

##### Chain: BSC

##### Coingecko ID (so your TVL can appear on Coingecko): gale-network

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): 19371

##### Short Description (to be shown on DefiLlama): GALE is a high yield sustainable deflationary compounding daily ROI platform on the BSC and Cronos network that pays you 1.2% interest daily with a daily compounding yield upto 7,778%

##### Token address and ticker if any: GALE - 0x627E86E9eC832b59018Bf91456599e752288Aa97

##### Category (full list at https://defillama.com/categories) *Please choose only one: 16- Staking

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

##### forkedFrom (Does your project originate from another project):

##### methodology (what is being counted as tvl, how is tvl being calculated): The TVL includes tokens locked in the Windmill CD contracts, the Treasury Vaults and the Liquidity pools.

2022-05-07 17:34 UTC, niftybrain commented
This is PR to get Gale listed on Defilama.

2022-05-08 06:33 UTC, llamatester commented
The adapter at projects/gale exports TVL: 
        
 
 
    bsc                       1.51 M
    bsc-treasury              206.50 k
    treasury                  206.50 k
    
    total                    1.51 M

2022-05-08 06:37 UTC, g1nt0ki requested changes

2022-05-08 06:37 UTC, g1nt0ki commented on projects/gale/index.js
> +    const liquidityBalance = (await sdk.api.abi.call({
sorry, you cannot add entire LP as your tvl, if you have staking contract, you could add that value under pool2

2022-05-08 06:37 UTC, g1nt0ki commented on projects/gale/index.js
> +    const treasuryBalance = (await sdk.api.abi.call({
only non-native tokens can be added as part of 'treasury' section. Again, it cannot be marked as tvl.

2022-05-08 06:37 UTC, g1nt0ki commented on projects/gale/index.js
> +    const treasuryBalance = (await sdk.api.abi.call({
ah, I see that you already have a separate treasury section, can you remove this code in tvl then, also update that section to only count non-native tokens

2022-05-08 06:37 UTC, g1nt0ki commented on projects/gale/index.js
> +    const totalDeposited = (await sdk.api.abi.call({
does this return the amount of GALE tokens that are burnt and never can be retrieved? if so, sorry but It cant be counted towards tvl, if the tokens can be retrieved by the user, it should still count towards 'staking' not tvl

2022-05-27 13:30 UTC, llamatester commented
The adapter at projects/gale exports TVL: 
        
 
 
    bsc                       0
    bsc-treasury              27.82 k
    bsc-staking               3.86 k
    treasury                  27.82 k
    staking                   3.86 k
    
    total                    0

2022-05-27 13:30 UTC, merged