Add Adapters for EcoDeFi
DefiLlama/DefiLlama-Adapters pull request #2716
Opened 2022-05-18 13:16 UTC by alexchang2022

##### Twitter Link:
https://twitter.com/esg_financial/

##### List of audit links if any:
https://www.certik.com/projects/esg-financial

##### Website Link:
https://ecodefi.net/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
https://ecodefi.net/img/img_logo_esg.7e50b672.png

##### Current TVL:
618,439 USD
##### Chain:
Binance Smart Chain(BSC)

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama):
The ESG Protocol is an Binance smart contract for supplying or borrowing assets. Through the eToken contracts, accounts on the blockchain supply capital (BNB or BEP-20 tokens) to receive eTokens or borrow assets from the protocol (holding other assets as collateral). The ESG eToken contracts track these balances and algorithmically set interest rates for borrowers.

##### Token address and ticker if any:
0x0985205D53D575CB07Dd4Fba216034dc614eab55

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

##### forkedFrom (Does your project originate from another project):
Compound

##### methodology (what is being counted as tvl, how is tvl being calculated):
Sum of total supply of underlying assets in every eTokens contract.

2022-05-18 19:12 UTC, llamatester commented
The adapter at projects/ecodefi exports TVL: 
        
 
 
    bsc-staking               11.11 k
    bsc                       612.36 k
    staking                   11.11 k
    
    total                    612.36 k

2022-05-19 08:48 UTC, g1nt0ki requested changes

2022-05-19 08:48 UTC, g1nt0ki commented on projects/ecodefi/index.js
> +	  tvl: bsc,
the staking part looks good, can you update the tvl computation part ot below, we have a helper that makes it easy to compute both deposits and borrowed amount:

    const { compoundExports } = require('../helper/compound');


    module.exports = {
      bsc: {
        ...compoundExports('0xfd1f241ba25b8966a14865cb22a4ea3d24c92451', 'bsc'),
        staking,
      },
    };

2022-05-20 01:52 UTC, alexchang2022 commented
Updated as required.
Please review it, thanks.

2022-05-20 05:55 UTC, llamatester commented
The adapter at projects/ecodefi exports TVL: 
        
 
 
    bsc                       541.51 k
    bsc-staking               907.6210268159999
    bsc-borrowed              54.91 k
    staking                   907.6210268159999
    borrowed                  54.91 k
    
    total                    541.51 k

2022-05-20 05:56 UTC, merged