Add JustMoney
DefiLlama/DefiLlama-Adapters pull request #3212
Opened 2022-07-11 05:08 UTC by salparadise93

**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI

---

##### Twitter Link:

https://twitter.com/JustMoneyIO

##### List of audit links if any:

##### Website Link:

https://about.just.money/

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

https://about.just.money/assets/img/logos/justmoney.svg

##### Current TVL:

697,317 USD

##### Chain:

Tron, BSC, Polygon, BitTorrent, Zenith

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

justmoney-2

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

19946

##### Short Description (to be shown on DefiLlama):

An ecosystem for the next generation of decentralized applications to power Web3 and DeFi.

##### Token address and ticker if any:

BSC, Polygon, BTTC: 0x388D819724dD6d71760A38F00dc01D310d879771
Tron: TVHH59uHVpHzLDMFFpUgCx2dNAQqCzPhcR

Ticker: JM

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Dexes

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

##### forkedFrom (Does your project originate from another project):

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL is calculated based on tokens in pools.

2022-07-11 20:51 UTC, llamatester commented
The adapter at projects/justmoney exports TVL: 
        
 
 
    tron                      483.73 k
    bsc                       135.59 k
    bittorrent                2.24 k
    polygon                   43.85 k
    
    total                    665.41 k

2022-07-12 07:30 UTC, g1nt0ki commented
@salparadise93 can you change to code to compute tvl using on chain calls instead? if you give me the factory contract addresses, I can help you with it :)

2022-07-12 12:47 UTC, salparadise93 commented
@g1nt0ki Thanks for the update. I've changed the code to use on chain calls for all chains except Tron. Could you provide any suggestions how it can be easily solved without API calls? Here is the factory contract address: `TBfTeNjh7k8PbkTad8z6WS2vqh7SQZUfQ8`. Also Bittorrent chain returns zeros, probably because of unknown assets.

p.s. I am not the part of the JustMoney team, but I can reach them via Telegram if needed.

2022-07-12 19:47 UTC, llamatester commented
The adapter at projects/justmoney exports TVL: 
        
 
 
    bittorrent                0
    bsc                       131.72 k
    polygon                   42.31 k
    tron                      360.68 k
    
    total                    534.71 k

2022-07-13 10:54 UTC, llamatester commented
The adapter at projects/justmoney exports TVL: 
        
 
 
    bittorrent                5.32 k
    bsc                       132.38 k
    polygon                   42.20 k
    tron                      353.25 k
    
    total                    533.14 k

2022-07-13 11:09 UTC, g1nt0ki requested changes

2022-07-13 11:09 UTC, g1nt0ki commented on projects/helper/portedTokens.js
> +  "TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR": {
this mapping is incorrect?

2022-07-13 11:09 UTC, g1nt0ki commented on projects/helper/portedTokens.js
> +  "TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR": {
ignore the comment, I see that you are compensating for 


    "0xedf53026aea60f8f75fca25f8830b7e2d6200662":
      "tron:TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR", // TRX

2022-07-13 11:09 UTC, g1nt0ki commented on projects/justmoney/index.js
> +  [ tokens.TRX, tokens.OLDJM, 'TFijK2dCUsrXoZM7PYhFqnM9F4Tac8uBJt' ],
this line is duplicate

2022-07-13 11:15 UTC, g1nt0ki commented
@salparadise93 really nice work. Bittorrent chain often fails on server, might end up disabling it.

2022-07-13 11:16 UTC, g1nt0ki commented
regarding no. of calls, it is not an issue, we batch it and multicall where we can. For tron, I think it is unavoidable.

2022-07-13 11:17 UTC, merged