add aurora TVL
DefiLlama/DefiLlama-Adapters pull request #3317
Opened 2022-07-21 13:53 UTC by oleksiivinogradov

**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Twitter Link:

##### List of audit links if any:

##### Website Link:

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

##### Current TVL:

##### Chain:

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama):

##### Token address and ticker if any:

##### Category (full list at https://defillama.com/categories) *Please choose only one:

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

##### forkedFrom (Does your project originate from another project):

##### methodology (what is being counted as tvl, how is tvl being calculated):

2022-07-21 13:53 UTC, llamatester commented
Error while running adapter at projects/MultiSwap: 
        
 
  
    
    
    Error: 
        Found export keys that were not part of specification: tvlAurora
    
        List of valid keys: 
    				
    				tvl
    				staking
    				methodology
    				pool2
    				misrepresentedTokens
    				fetch
    				timetravel
    				borrowed
    				start
    				masterchef
    				doublecounted
    				treasury
    				hallmarks
    				incentivized
    				offers
    				deadFrom
    				broken
    				ownTokens

2022-07-21 15:05 UTC, g1nt0ki requested changes

2022-07-21 15:05 UTC, g1nt0ki commented on projects/MultiSwap/index.js
> +    tvlAurora
change this to `tvl: tvlAurora`

2022-07-22 07:54 UTC, oleksiivinogradov commented on projects/MultiSwap/index.js
> +    tvlAurora
done

2022-07-22 07:54 UTC, llamatester commented
Error while running adapter at projects/MultiSwap: 
        
 
  
    
    
    Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="poolsCount()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.4)
    Truncated error stack:
        at Interface.decodeFunctionResult (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/@ethersproject/abi/lib/interface.js:388:23)

2022-07-22 07:55 UTC, oleksiivinogradov commented
fixed

2022-07-22 15:04 UTC, llamatester commented
The adapter at projects/MultiSwap exports TVL: 
        
 
 
    aurora                    0.00000767186748
    kava                      0.07572396235893525
    
    total                    0.07573163422641525

2022-07-22 15:06 UTC, merged