Add pine protocol support
DefiLlama/DefiLlama-Adapters pull request #4877
Opened 2022-12-14 14:29 UTC by jupiteruwdev

**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

##### Twitter Link:

##### List of audit links if any:

##### Website Link:

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

##### Current TVL:

##### Chain:

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama):

##### Token address and ticker if any:

##### Category (full list at https://defillama.com/categories) *Please choose only one:

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

##### forkedFrom (Does your project originate from another project):

##### methodology (what is being counted as tvl, how is tvl being calculated):

2022-12-14 14:30 UTC, llamatester commented
The adapter at projects/pine-protocol exports TVL: 
        
 
 
    ethereum                  496.05 k
    
    total                    496.05 k

2022-12-14 17:02 UTC, g1nt0ki commented
@jupiteruwdev can you please fill in  the project details in PR description

2022-12-14 17:06 UTC, g1nt0ki commented
how are you pricing the NFTs? can you update the adapter to compute tvl using onchain calls, let me know if you need some help wth that

2022-12-14 17:07 UTC, g1nt0ki requested changes
.

2022-12-14 17:42 UTC, jupiteruwdev commented
> 

We've a lot of pools and we don't have an aggregated pool or contract for calculating tvl. But we're calculating in our backend service which is currently used in tvl function.

2022-12-14 17:42 UTC, jupiteruwdev commented
> how are you pricing the NFTs? can you update the adapter to compute tvl using onchain calls, let me know if you need some help wth that

We've a lot of pools and we don't have an aggregated pool or contract for calculating tvl. But we're calculating in our backend service which is currently used in tvl function.

2022-12-15 16:45 UTC, g1nt0ki commented
right now it is a complete blackbox, can you expose the pool list via an api? and then use it in the adapter? Also, how are you pricing the NFTs?

2022-12-15 17:36 UTC, jupiteruwdev commented
> right now it is a complete blackbox, can you expose the pool list via an api? and then use it in the adapter? Also, how are you pricing the NFTs?

Sure, will do. We're relying on third party resources like - alchemy, opensea, gemxyz, ...

2022-12-16 12:54 UTC, llamatester commented
Error while running adapter at projects/pine-protocol: 
        
 
  
    
    
    Error: connect ECONNREFUSED 127.0.0.1:8080
    Truncated error stack:
    
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)

2022-12-20 10:48 UTC, g1nt0ki requested changes

2022-12-22 13:27 UTC, jupiteruwdev commented on projects/pine-protocol/index.js
> +    "http://localhost:8080/v0/pools/addresses?ethereum=1"
Yes, the api is not deployed on prod so I'll update it later whenever it's deployed.

2023-02-21 07:25 UTC, merged

2023-02-21 07:26 UTC, g1nt0ki commented
@jupiteruwdev I have updated it to use logs here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/ec8f0a6a5ed48627ebb6ba1533ded4ffecf111ae