Feat: update tvl fetched from staking pools / vault / vesting / lock …
DefiLlama/DefiLlama-Adapters pull request #4915
Opened 2022-12-20 15:54 UTC by DramaCrypto

…contracts

**NOTE**

> If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).

1. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
2. The protocol is usually listed within 24 hours of merging the PR
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

##### Twitter Link:

##### List of audit links if any:

##### Website Link:

##### Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):

##### Current TVL:

##### Chain:

##### Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama):

##### Token address and ticker if any:

##### Category (full list at https://defillama.com/categories) *Please choose only one:

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

##### forkedFrom (Does your project originate from another project):

##### methodology (what is being counted as tvl, how is tvl being calculated):

2022-12-20 15:54 UTC, llamatester commented
The adapter at projects/candycity exports TVL: 
        
 
 
    cronos                    3.14 M
    
    total                    3.14 M

2022-12-21 16:16 UTC, g1nt0ki requested changes
hi @DramaCrypto 

Sorry, but we cant count candy tokens under tvl.
We can count the user staked tokens under 'staking'
and the vested candy tokens under 'vesting'

https://docs.llama.fi/list-your-project/what-to-include-as-tvl

2022-12-26 13:22 UTC, llamatester commented
The adapter at projects/candycity exports TVL: 
        
 
 
    cronos-vesting            1.06 M
    cronos-staking            2.31 M
    cronos                    3.47 M
    vesting                   1.06 M
    staking                   2.31 M
    
    total                    3.47 M

2022-12-26 13:25 UTC, DramaCrypto commented
I added vesting and staking as you commented @g1nt0ki

2022-12-26 19:53 UTC, g1nt0ki requested changes

2022-12-26 19:53 UTC, g1nt0ki commented on projects/candycity/index.js
> +    tvl:  sdk.util.sumChainTvls([chainTvl, fetchTvl]),
@DramaCrypto changed this line to `tvl:  chainTvl,` then it is good, else staking would be double counted

2022-12-26 23:46 UTC, g1nt0ki commented on projects/candycity/index.js
> +    tvl:  sdk.util.sumChainTvls([chainTvl, fetchTvl]),
I will fix this

2022-12-26 23:47 UTC, merged