Added VEGA in asset pool to TVL, added methodology, added Vesting
DefiLlama/DefiLlama-Adapters pull request #6507
Opened 2023-06-08 05:14 UTC by C0deMunk33

Added VEGA in asset pool to TVL, added methodology, added Vesting.

2023-06-08 05:14 UTC, llamatester commented
The adapter at projects/vega-protocol exports TVL: 
        
 
 
    ethereum-vesting          43.74 M
    ethereum-staking          43.43 M
    ethereum                  3.61 M
    vesting                   43.74 M
    staking                   43.43 M
    
    total                    3.61 M

2023-06-08 07:14 UTC, g1nt0ki requested changes
.

2023-06-08 07:14 UTC, g1nt0ki commented on projects/vega-protocol/index.js
> -      if (vega) blacklistedTokens.push(vega)
sorry, this needs to be retained, we dont count count own tokens as tvl as it costs the protocol nothing to inflate tvl.

2023-06-08 07:14 UTC, g1nt0ki commented on projects/vega-protocol/index.js
>          '0xcb84d72e61e383767c4dfeb2d8ff7f4fb89abc6e': BigNumber(vegaStakedInVesting).plus(BigNumber(vegaStakedInStaking)).toFixed(0)
okay, I am seeing the same tokens counted in two places (staking & vesting) (?)

The mistake might be on my part for including it in staking, are these tokens in circulation, or they being vested and investors/team get their hands on it for the first time after they get unlocked at certain time?

2023-06-21 16:04 UTC, g1nt0ki commented
closing because of inactivity

2023-06-21 16:04 UTC, closed without merging