Fixed Ambire Wallet staking and added Ambire TVL for wallet rewards
DefiLlama/DefiLlama-Adapters pull request #8363
Opened 2023-12-12 11:11 UTC by stojnovsky

**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Please enable "Allow edits by maintainers" while putting up the PR.
3. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama):

##### Twitter Link:

##### List of audit links if any:

##### Website Link:

##### Logo (High resolution, will be shown with rounded borders):

##### Current TVL:

##### Treasury Addresses (if the protocol has treasury)

##### Chain:

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama):

##### Token address and ticker if any:

##### Category (full list at https://defillama.com/categories) *Please choose only one:

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

##### forkedFrom (Does your project originate from another project):

##### methodology (what is being counted as tvl, how is tvl being calculated):

##### Github org/user (Optional, if your code is open source, we can track activity):

2023-12-12 11:12 UTC, llamatester commented
The adapter at projects/ambire-wallet exports TVL: 
        
 
 
    ethereum-staking          3.23 M
    ethereum                  22.15 M
    staking                   3.23 M
    
    total                    22.15 M

2023-12-12 15:34 UTC, g1nt0ki commented on projects/ambire-wallet/ambireTVLContracts.js
these are multisig addresses generated by ambire? if so, we cant count it as tvl. 

I would kindly request you to remove these from tvl

2023-12-12 15:37 UTC, g1nt0ki commented on projects/ambire-wallet/helpers.js
> +      [ADEX_staking]: parseInt(sharedValues.output[1].output) / 1e18
I too am equally perplexed why we were count adax staking under ambire in the past, is there some link between the two?

2023-12-12 16:55 UTC, g1nt0ki requested changes
.

2023-12-25 15:07 UTC, g1nt0ki commented
closed as there was no answer

2023-12-25 15:07 UTC, closed without merging