add Lessgas
DefiLlama/DefiLlama-Adapters pull request #8893
Opened 2024-02-08 03:41 UTC by IvanMacaron

##### Name (to be shown on DefiLlama):
Lessgas

##### Twitter Link:
https://twitter.com/Less_Gas

##### List of audit links if any:

##### Website Link:
https://lessgas.xyz

##### Logo (High resolution, will be shown with rounded borders):
![icon_logo](https://github.com/DefiLlama/DefiLlama-Adapters/assets/92434329/601c197f-e2ca-44b3-ad5a-05ace3cbfcc4)

##### Current TVL:
Map Protocol： 5.42 M USDT

##### Treasury Addresses (if the protocol has treasury)

##### Chain:
 Map Protocol

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama):
Bitcoin Layer2 inscription platform with ultra-low gas fees,zero failures,and zero congestion

##### Token address and ticker if any:
$LSGS Map Protocol 0x756af1d3810a01d3292fad62f295bbcc6c200aea
$LSGS Bitcore 4667a31423135f0fe7e8ce3cd8aa60cb493e9e201e8135785a1c7fcda7a52c0ci0

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Launchpad

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

##### forkedFrom (Does your project originate from another project):
No, it is built on our own

##### methodology (what is being counted as tvl, how is tvl being calculated):

##### Github org/user (Optional, if your code is open source, we can track activity):

2024-02-08 03:42 UTC, llamatester commented
The adapter at projects/lessgas exports TVL: 
        
 
 
    map-staking               1.67 M
    map                       5.41 M
    staking                   1.67 M
    
    total                    5.41 M

2024-02-08 05:55 UTC, g1nt0ki requested changes
Please refactor code to compute tvl on chain, in it's current state, I have no idea what is counted as tvl

2024-02-08 06:26 UTC, llamatester commented
Error while running adapter at projects/lessgas: 
        
 
  
    
    
    Error: connect ECONNREFUSED 127.0.0.1:9912
    Truncated error stack:
        at AxiosError.from (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/node_modules/axios/dist/node/axios.cjs:837:14)
        at RedirectableRequest.emit (node:events:517:28)
        at ClientRequest.emit (node:events:517:28)
        at Socket.socketErrorListener (node:_http_client:501:9)
        at Socket.emit (node:events:517:28)

2024-02-08 06:38 UTC, g1nt0ki requested changes
none of these tokens are in coingecko, we rely on their api for price, and why are you counting token supply as tvl? https://docs.llama.fi/list-your-project/what-to-include-as-tvl

2024-02-08 07:44 UTC, llamatester commented
The adapter at projects/lessgas exports TVL: 
        
 
 
    map-staking               1.67 M
    map                       5.42 M
    staking                   1.67 M
    
    total                    5.42 M

2024-02-20 03:23 UTC, llamatester commented
The adapter at projects/lessgas exports TVL: 
        
 
 
    map                       1.34 M
    map-staking               1.34 M
    staking                   1.34 M
    
    total                    1.34 M

2024-02-20 14:31 UTC, g1nt0ki commented
> none of these tokens are in coingecko, we rely on their api for price, and why are you counting token supply as tvl? https://docs.llama.fi/list-your-project/what-to-include-as-tvl

@IvanMacaron you are double counting staking as tvl, we cant use your rest api for pricing tokens, for pulling token list it is fine (we cache api response on our end)

2024-02-21 07:50 UTC, IvanMacaron commented
Hello sir, I am confused about the price. I do not know how to obtain the price from the API you provided. Can you please let me know specifically so that I can modify the relevant code and complete the data adaptation

2024-02-22 03:05 UTC, llamatester commented
The adapter at projects/lessgas exports TVL: 
        
 
 
    map                       0
    map-staking               1.44 M
    staking                   1.44 M
    
    total                    0

2024-02-22 08:25 UTC, g1nt0ki commented on projects/lessgas/index.js
> +     total =  new BigNumber(total).plus(new BigNumber(output).div(10**18).multipliedBy(new BigNumber(item[2])));
I am talking about this line, item[2] here is the price right? we use our own api for pulling token price, for example xcCGF on moonbeam: https://coins.llama.fi/prices/current/moonbeam:0xffffffff44bd9d2ffee20b25d1cf9e78edb6eae3

We dont have a token list for map tokens, so currently it is returning 0

2024-02-22 08:27 UTC, g1nt0ki commented on projects/lessgas/index.js
> +     total =  new BigNumber(total).plus(new BigNumber(output).div(10**18).multipliedBy(new BigNumber(item[2])));
do you know of an official bridge, that I can use to map map tokens to brc20 on bitcoin, and/or what tokens on map  chain are listed on coingecko? without these info we cant price tokens on map

2024-02-26 10:49 UTC, g1nt0ki commented
@IvanMacaron how are you pricing LSGS token? I dont find it on coingecko, so unsure how to price it

2024-02-27 11:56 UTC, IvanMacaron commented
> @IvanMacaron how are you pricing LSGS token? I dont find it on coingecko, so unsure how to price it
Sir,
We are submitting our price information to Coinsecko，
I will inform you as soon as the submission is successful

2024-03-04 04:46 UTC, IvanMacaron commented
> @IvanMacaron how are you pricing LSGS token? I dont find it on coingecko, so unsure how to price it

Sir,
Our prices can already be found on Coinsecko. How should I make adaptation modifications below?

2024-03-06 09:17 UTC, llamatester commented
The adapter at projects/lessgas exports TVL: 
        
 
 
    map                       0
    map-staking               0
    staking                   0
    
    total                    0

2024-03-06 09:18 UTC, g1nt0ki commented
@IvanMacaron sorry for the delay, I have added code to price LSGS tokens on our server repo. https://github.com/DefiLlama/defillama-server/commit/3b2a337f1ca4a5dd7d0386c8f121046156f3db37 so, LSGS will have price in 2-3 hours.

2024-03-06 09:18 UTC, merged

2024-03-07 08:10 UTC, IvanMacaron commented
Sir，
Coinmarketcap supports the MAP Protocol main network, and other token prices on the MAP Protocol main network can be retrieved from Coinmarketcap. May I ask if it supports TVL for stacking other tokens included in Lessgas