feat: add Fixes Inscription Protocol on Flow
DefiLlama/DefiLlama-Adapters pull request #9058
Opened 2024-02-25 06:45 UTC by btspoony

**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

---

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
5. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): 

FIXeS Protocol

##### Twitter Link:

https://twitter.com/fixesOnFlow

##### List of audit links if any:

N/A

##### Website Link:

https://fixes.world/

##### Logo (High resolution, will be shown with rounded borders):

![FIXeS Logo-512x512](https://github.com/DefiLlama/DefiLlama-Adapters/assets/707025/89eac2fe-dcb5-432d-bc00-0e6579c709fe)

##### Current TVL:

129.56K $FLOW
 
![image](https://github.com/DefiLlama/DefiLlama-Adapters/assets/707025/88a461bb-a44e-49fe-b27b-6a454db3a732)
![image](https://github.com/DefiLlama/DefiLlama-Adapters/assets/707025/7f982373-2ee2-44f3-b0e1-2814d77a424a)

##### Treasury Addresses (if the protocol has treasury)

https://www.flowdiver.io/account/0xd2abb5dbf5e08666

_This is the contract address, $FLOW in Treasury is locked inside the contract address_ 

##### Chain:

Flow

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

N/A

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

N/A

##### Short Description (to be shown on DefiLlama):

FIXeS is an executable inscription protocol on Flow blockchain. It allows users to inscribe anything on the blockchain and also provides the 𝔉rc20 fungible tokens.

##### Token address and ticker if any:

Official Ticker: $FLOWS, $FIXES

##### Category (full list at https://defillama.com/categories) *Please choose only one:

[Services](https://defillama.com/protocols/Services)

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

##### forkedFrom (Does your project originate from another project):

Original

##### methodology (what is being counted as tvl, how is tvl being calculated):

TVL Methodology:

- Treasury Pool: When minting 𝔉rc20 fungible tokens, $FLOW (minting cost) will be deposited into the Treasury Pool. If 𝔉rc20 is a burnable token, users can retrieve $FLOW from the Treasury Pool through the **burn** operation.
- Staking Pool: Users can stake their 𝔉rc20 tokens to receive benefits, such as fee sharing and 𝔉rc20 token vesting. Currently, only $FLOWS staking is open.

Docs: <https://docs.fixes.world/>

##### Github org/user (Optional, if your code is open source, we can track activity):

<https://github.com/fixes-world/>

2024-02-25 06:45 UTC, llamatester commented
The adapter at projects/fixes-frc20-staking exports TVL: 
        
 
 
    flow                      36.12 k
    
    total                    36.12 k

2024-02-25 06:46 UTC, llamatester commented
The adapter at projects/fixes-frc20 exports TVL: 
        
 
 
    flow                      93.51 k
    
    total                    93.51 k

2024-02-26 16:15 UTC, g1nt0ki commented
hi @btspoony thanks for the PR

Counting the treasury value as tvl as they can be burned to get back the FLOW makes sense, but I dont agree with liquid staking part, these are tokens minted by your protocol whose value is already counted as tvl, also, Liquid staking is meant for staking derivative like Lido ETH for ETH, i.e native/gas token of chain is locked/staked via some protocol, dont think that applies to your case.

I can merge this PR after you remove "projects/fixes-frc20-staking"?

2024-02-26 16:16 UTC, g1nt0ki requested changes
.

2024-02-27 02:09 UTC, btspoony commented
> hi @btspoony thanks for the PR
> 
> Counting the treasury value as tvl as they can be burned to get back the FLOW makes sense, but I dont agree with liquid staking part, these are tokens minted by your protocol whose value is already counted as tvl, also, Liquid staking is meant for staking derivative like Lido ETH for ETH, i.e native/gas token of chain is locked/staked via some protocol, dont think that applies to your case.
> 
> I can merge this PR after you remove "projects/fixes-frc20-staking"?

hi @g1nt0ki 

Staking Part is indeed the Token minted by my protocol.

But in the Stake operation, they are locked again (cannot circulate on the Market, but users can obtain a SemiNFT as proof).
Because of the existence of the Market, these Tokens have a token value(Floor Price) higher than the Treasury Pool value.

---

Can I count the `(Market Token Value - Treasure Pool Benchmark Value) * Staked Amount` as TVL?

2024-02-27 02:17 UTC, llamatester commented
The adapter at projects/fixes-frc20-staking exports TVL: 
        
 
 
    flow                      50.60 k
    
    total                    50.60 k

2024-02-27 02:17 UTC, llamatester commented
The adapter at projects/fixes-frc20 exports TVL: 
        
 
 
    flow                      102.78 k
    
    total                    102.78 k

2024-02-27 02:22 UTC, llamatester commented
The adapter at projects/fixes-frc20-staking exports TVL: 
        
 
 
    flow                      50.60 k
    
    total                    50.60 k

2024-02-27 02:22 UTC, llamatester commented
The adapter at projects/fixes-frc20 exports TVL: 
        
 
 
    flow                      102.78 k
    
    total                    102.78 k

2024-02-27 02:27 UTC, btspoony commented
> hi @btspoony thanks for the PR
> 
> Counting the treasury value as tvl as they can be burned to get back the FLOW makes sense, but I dont agree with liquid staking part, these are tokens minted by your protocol whose value is already counted as tvl, also, Liquid staking is meant for staking derivative like Lido ETH for ETH, i.e native/gas token of chain is locked/staked via some protocol, dont think that applies to your case.
> 
> I can merge this PR after you remove "projects/fixes-frc20-staking"?



> hi @btspoony thanks for the PR
> 
> Counting the treasury value as tvl as they can be burned to get back the FLOW makes sense, but I dont agree with liquid staking part, these are tokens minted by your protocol whose value is already counted as tvl, also, Liquid staking is meant for staking derivative like Lido ETH for ETH, i.e native/gas token of chain is locked/staked via some protocol, dont think that applies to your case.
> 
> I can merge this PR after you remove "projects/fixes-frc20-staking"?

Changed to the new methodology I mentioned, please take a look and see if this can be considered as TVL.
It subtracted the portion in Treasury Pool that is already calculated as TVL (which is Benchmark Value).

2024-02-27 02:35 UTC, btspoony commented on projects/fixes-frc20-staking/index.js
> +        totalTVL = totalTVL + (validStaked * (floorPrice - benchmarkPrice))
New Staking TVL Methodolgy:
TVL: validStaked * (floorPrice - benchmarkPrice)

2024-02-27 09:00 UTC, merged