Update/bifi
DefiLlama/DefiLlama-Adapters pull request #9896
Opened 2024-04-19 04:46 UTC by tlatkdgus1

##### Name (to be shown on DefiLlama): BiFi

##### Twitter Link: https://twitter.com/bifi_lending

##### List of audit links if any: 
https://github.com/bifrost-platform/BIFI/blob/master/docs/ENG/(ENG)_BiFi_BIFROST_Extension_Theori.pdf
https://github.com/bifrost-platform/BIFI/blob/master/docs/ENG/(ENG)_BiFi_Lending_Sooho_EN_Public.pdf
https://github.com/bifrost-platform/BIFI/blob/master/docs/ENG/(ENG)_BiFi_Token_Hexlant_EN.pdf
https://github.com/bifrost-platform/BIFI/blob/master/docs/ENG/(ENG)_BiFrost_BTC_Extension_CertiK.pdf
https://github.com/bifrost-platform/BiFi-X/blob/main/docs/bifrost_bifix_audit.pdf

##### Website Link: https://crosschain.bifi.finance/

##### Logo (High resolution, will be shown with rounded borders): https://raw.githubusercontent.com/bifrost-platform/AssetInfo/master/Protocols/images/bifi.png

##### Current TVL: 29,710,000

##### Treasury Addresses (if the protocol has treasury)

##### Chain: Bifrost Mainnet, Ethereum, BNB Chain, Polygon, Arbitrum, Base

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

##### Short Description (to be shown on DefiLlama): Cross-chain collateralized lending with native assets - powered by Bifrost network. Utilize Ethereum, BNB, and Matic, directly from their native chains.

##### Token address and ticker if any:

##### Category (full list at https://defillama.com/categories) *Please choose only one: Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):

##### forkedFrom (Does your project originate from another project): N/A

##### methodology (what is being counted as tvl, how is tvl being calculated): BiFi is a crosschain lending platform. To calculate the TVL of BiFi, we add all the deposited token and subtract borrowed amount of tokens

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/bifrost-platform/BIFI

2024-04-19 04:48 UTC, llamatester commented
The adapter at projects/bifi exports TVL: 
        
 
 
    bitcoin                   22.90 M
    bfc                       6.10 M
    ethereum                  1.05 M
    bsc                       831.75 k
    klaytn                    125.72 k
    avax                      101.12 k
    ethereum-staking          34.17 k
    staking                   34.17 k
    
    total                    31.11 M

2024-04-19 04:56 UTC, tlatkdgus1 commented
Hi Team! I have question.

our stable coin not registered yet in coingecko

so,  I token mapped btcusd -> usdc

I guess this issue related about my another PR
> https://github.com/DefiLlama/DefiLlama-Adapters/pull/9888#issuecomment-2065743951

2024-04-19 09:55 UTC, g1nt0ki commented on projects/helper/tokenMapping.js
> +    '0x6906Ccda405926FC3f04240187dd4fAd5DF6d555': { coingeckoId: "usd-coin", decimals: 18, },
hi @tlatkdgus1 most of the PR is good, except for this part. BtcUSD is not USDC, can wait for coingecko listing before adding it here, another option is, if you share some uni v2/v3 pool with enough liquidity, we can use it to price it in our server.

2024-04-19 09:55 UTC, g1nt0ki requested changes
.

2024-04-19 10:45 UTC, g1nt0ki commented
> Hi Team! I have question.
> 
> our stable coin not registered yet in coingecko
> 
> so, I token mapped btcusd -> usdc
> 
> I guess this issue related about my another PR
> 
> > [#9888 (comment)](https://github.com/DefiLlama/DefiLlama-Adapters/pull/9888#issuecomment-2065743951)

missed this comment, sorry, dont like the idea of linking to usdc gecko id

2024-05-16 12:22 UTC, g1nt0ki commented
merged here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/10246

2024-05-16 12:22 UTC, closed without merging