Add TradingStrategy.ai
DefiLlama/DefiLlama-Adapters pull request #9966
Opened 2024-04-24 23:18 UTC by miohtama

Internal PR to see what CI says

2024-04-24 23:19 UTC, llamatester commented
The adapter at projects/trading-strategy exports TVL: 
        
 
 
    polygon                   13.28 k
    ethereum                  0
    bsc                       0
    base                      0
    arbitrum                  0
    
    total                    13.28 k

2024-04-25 10:29 UTC, g1nt0ki requested changes
hi, your app has two issues, the open strategies are enzyme contracts, which we already count as part of enzyme tvl

And the hot wallets being hot wallets, we cant include as tvl. So, I am not sure if we can list you  :(

2024-04-25 10:29 UTC, g1nt0ki commented on projects/trading-strategy/index.js
this can be reduced to 

    const { getConfig } = require('../helper/cache')

    const chains = ["ethereum", "polygon", "base", "bsc", "arbitrum"]

    chains.forEach(chain => {
      module.exports[chain] = {
        tvl: async (api) => {
          const { strategies } = await getConfig('trading-strategy', 'https://tradingstrategy.ai/strategies/tvl')
          const vaults = Object.values(strategies).filter(strat => strat.chain_id === api.chainId && strat.asset_management_mode === 'enzyme').map(i => i.address)
          const tokens = await api.multiCall({ abi: 'address[]:getTrackedAssets', calls: vaults })
          return api.sumTokens({ ownerTokens: tokens.map((t, i) => [t, vaults[i]])})
        }
      }
    })

2024-04-25 11:22 UTC, miohtama commented on projects/trading-strategy/index.js
Thank you for getting back @g1nt0ki.

What if I exclude our vaults from Enzyme contracts? I can speak with Enzyme about this, as we are in good terms.

2024-04-29 12:16 UTC, miohtama commented
@g1nt0ki ping here - please see the question above

2024-04-29 13:37 UTC, g1nt0ki commented
hi @miohtama sorry for the delayed response. Trying to understand the product a bit more, how does TradingStrategy UI interact with emzyme contracts, directly? or you have deployed your own contracts, that act as proxy/controller?

2024-05-20 11:44 UTC, miohtama commented
Thank you for your response @g1nt0ki 

- We use Enzyme vaults
- You can interact the same vaults through Enzyme frontend and TradingStrategy.ai frontend
- Vaults that are Trading Strategy enabled have a special configuration on Enzyme - it is an extensible protocol after all
- The configuration changes enabled to have oracle-based asset manager (instead of "human" asset managers that's Enzyme default)
- There are our own contracts deployed, but they are set as guard and asset manager roles in Enzyme vaults, the core Comproller and Vault contracts are still Enzyme defaults (they are immutable, they cannot be changed in fact)

Hope this helps.

2024-05-21 07:35 UTC, g1nt0ki commented
hi @miohtama 

Sorry, we cant show tvl in that case. But do you charge some fees? if so, we can pull and show the revenue/fee metric.

Checked with the team, same will be applicable to the teams building on top of uni v4.

2025-06-05 11:19 UTC, llamabutler commented
The adapter at projects/trading-strategy exports TVL: 
        
 
 
    ethereum                  27.34 k
    arbitrum                  23.36 k
    polygon                   9.34 k
    bsc                       0
    base                      0
    
    total                    60.04 k

2025-06-05 13:25 UTC, g1nt0ki commented
we finally have a category that fits: https://defillama.com/protocols/onchain-capital-allocator

merged this with some changes here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/14943

2025-06-05 13:25 UTC, closed without merging